public class GUINewTask extends javax.swing.JFrame {
    
    //Globale Variablen
    ControlGUI ControlGUI1;

    //Konstruktor
    public GUINewTask(ControlGUI aControlGUI) {
        ControlGUI1 = aControlGUI;
        initComponents();
    }
    
    //get alle ausgewählte User
    public String getUseres(){
        
        String sUsernames = txfToUser.getText();
        return sUsernames;
    }
    
    //
    public String getSubject(){
    String sSubject = txfSubject.getText();
    return sSubject;
    }
    
    //
    public String getDescription(){
    String sDescription = txaTaskDescription.getText();
    return sDescription;
}
            
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNewTaskBackground = new javax.swing.JPanel();
        btnNewTaskCancel = new javax.swing.JButton();
        scTXATaskDescription = new javax.swing.JScrollPane();
        txaTaskDescription = new javax.swing.JTextArea();
        txfSubject = new javax.swing.JTextField();
        lblSubject = new javax.swing.JLabel();
        btnToUser = new javax.swing.JButton();
        txfToUser = new javax.swing.JTextField();
        btnSendTask = new javax.swing.JButton();
        btnSaveTask = new javax.swing.JButton();
        lblTimeNeeded = new javax.swing.JLabel();
        spZeitaufwand = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Neue Aufgaben verfassen");
        setMinimumSize(new java.awt.Dimension(858, 480));

        PanelNewTaskBackground.setBackground(new java.awt.Color(40, 40, 40));
        PanelNewTaskBackground.setMaximumSize(new java.awt.Dimension(858, 480));
        PanelNewTaskBackground.setMinimumSize(new java.awt.Dimension(858, 480));

        btnNewTaskCancel.setBackground(new java.awt.Color(18, 110, 99));
        btnNewTaskCancel.setForeground(new java.awt.Color(145, 237, 228));
        btnNewTaskCancel.setText("Abbrechen");
        btnNewTaskCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTaskCancelActionPerformed(evt);
            }
        });

        txaTaskDescription.setBackground(new java.awt.Color(18, 110, 99));
        txaTaskDescription.setColumns(20);
        txaTaskDescription.setForeground(new java.awt.Color(145, 237, 228));
        txaTaskDescription.setRows(5);
        scTXATaskDescription.setViewportView(txaTaskDescription);

        txfSubject.setBackground(new java.awt.Color(18, 110, 99));
        txfSubject.setForeground(new java.awt.Color(145, 237, 228));

        lblSubject.setBackground(new java.awt.Color(18, 110, 99));
        lblSubject.setForeground(new java.awt.Color(145, 237, 228));
        lblSubject.setText("Betreff: ");

        btnToUser.setBackground(new java.awt.Color(18, 110, 99));
        btnToUser.setForeground(new java.awt.Color(145, 237, 228));
        btnToUser.setText("An:");
        btnToUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToUserActionPerformed(evt);
            }
        });

        txfToUser.setBackground(new java.awt.Color(18, 110, 99));
        txfToUser.setForeground(new java.awt.Color(145, 237, 228));

        btnSendTask.setBackground(new java.awt.Color(18, 110, 99));
        btnSendTask.setForeground(new java.awt.Color(145, 237, 228));
        btnSendTask.setText("Task abschicken");

        btnSaveTask.setBackground(new java.awt.Color(18, 110, 99));
        btnSaveTask.setForeground(new java.awt.Color(145, 237, 228));
        btnSaveTask.setText("Task speichern");
        btnSaveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTaskActionPerformed(evt);
            }
        });

        lblTimeNeeded.setBackground(new java.awt.Color(18, 110, 99));
        lblTimeNeeded.setForeground(new java.awt.Color(145, 237, 228));
        lblTimeNeeded.setText("Zeitaufwand in min.: ");

        spZeitaufwand.setMaximumSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout PanelNewTaskBackgroundLayout = new javax.swing.GroupLayout(PanelNewTaskBackground);
        PanelNewTaskBackground.setLayout(PanelNewTaskBackgroundLayout);
        PanelNewTaskBackgroundLayout.setHorizontalGroup(
            PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSendTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewTaskCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveTask)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelNewTaskBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSubject)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelNewTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNewTaskBackgroundLayout.createSequentialGroup()
                        .addComponent(btnToUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfSubject)
                            .addGroup(PanelNewTaskBackgroundLayout.createSequentialGroup()
                                .addComponent(txfToUser, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                                .addGap(31, 31, 31)
                                .addComponent(lblTimeNeeded)
                                .addGap(18, 18, 18)
                                .addComponent(spZeitaufwand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(scTXATaskDescription, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PanelNewTaskBackgroundLayout.setVerticalGroup(
            PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendTask)
                    .addComponent(btnNewTaskCancel)
                    .addComponent(btnSaveTask))
                .addGap(18, 18, 18)
                .addGroup(PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToUser)
                    .addComponent(txfToUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spZeitaufwand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeNeeded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(txfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scTXATaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNewTaskBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNewTaskBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToUserActionPerformed
        //GUIToUser wird sichtbar gemacht
        ControlGUI1.setGUIToUserVisible();
    }//GEN-LAST:event_btnToUserActionPerformed

    private void btnNewTaskCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTaskCancelActionPerformed
        //GUINewTask1.setVisible(false); oder noch besser etwas das das Fenster wirklich schließt.
        ControlGUI1.setGUINewTaskInvisible();
    }//GEN-LAST:event_btnNewTaskCancelActionPerformed

    private void btnSaveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTaskActionPerformed
        //"txaTaskDescription","txfSubject","txfToUser" und "spZeitaufwand" auslesen und in Datenbank für User Hinterlegen
    }//GEN-LAST:event_btnSaveTaskActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNewTaskBackground;
    private javax.swing.JButton btnNewTaskCancel;
    private javax.swing.JButton btnSaveTask;
    private javax.swing.JButton btnSendTask;
    private javax.swing.JButton btnToUser;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTimeNeeded;
    private javax.swing.JScrollPane scTXATaskDescription;
    private javax.swing.JSpinner spZeitaufwand;
    private javax.swing.JTextArea txaTaskDescription;
    private javax.swing.JTextField txfSubject;
    private javax.swing.JTextField txfToUser;
    // End of variables declaration//GEN-END:variables
}
