/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projektuitest;

/**
 *
 * @author F
 */
public class GUITaskAnsicht extends javax.swing.JFrame {

    /**
     * Creates new form UITaskAnicht
     */
    public GUITaskAnsicht() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngFinishQuestion = new javax.swing.ButtonGroup();
        PanelTaskBackground = new javax.swing.JPanel();
        btnTaskAnsichtExit = new javax.swing.JButton();
        btnNewTask = new javax.swing.JButton();
        btnMyTasks = new javax.swing.JButton();
        scpTXATaskDescription = new javax.swing.JScrollPane();
        txaTaskDescription = new javax.swing.JTextArea();
        btnTaskFinish = new javax.swing.JButton();
        scpLSTAllTasks = new javax.swing.JScrollPane();
        lstAllTasks = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        btnQuestion = new javax.swing.JButton();
        lblVonUser = new javax.swing.JLabel();
        lblEingeschätzteZeit = new javax.swing.JLabel();
        txfVonUser = new javax.swing.JTextField();
        txfEingeschätzteZeit = new javax.swing.JTextField();
        txfTatsaechlicheZeit = new javax.swing.JTextField();
        lblTatsaechlicheZeit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Programm Name] Meine Aufgaben");
        setMaximumSize(new java.awt.Dimension(858, 480));
        setMinimumSize(new java.awt.Dimension(858, 480));

        PanelTaskBackground.setBackground(new java.awt.Color(40, 40, 40));
        PanelTaskBackground.setMaximumSize(new java.awt.Dimension(858, 480));
        PanelTaskBackground.setMinimumSize(new java.awt.Dimension(858, 480));
        PanelTaskBackground.setPreferredSize(new java.awt.Dimension(858, 480));

        btnTaskAnsichtExit.setBackground(new java.awt.Color(18, 110, 99));
        btnTaskAnsichtExit.setForeground(new java.awt.Color(145, 237, 228));
        btnTaskAnsichtExit.setText("EXIT");
        btnTaskAnsichtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskAnsichtExitActionPerformed(evt);
            }
        });

        btnNewTask.setBackground(new java.awt.Color(18, 110, 99));
        btnNewTask.setForeground(new java.awt.Color(145, 237, 228));
        btnNewTask.setText("Neue Aufgabe");
        btnNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTaskActionPerformed(evt);
            }
        });

        btnMyTasks.setBackground(new java.awt.Color(18, 110, 99));
        btnMyTasks.setForeground(new java.awt.Color(145, 237, 228));
        btnMyTasks.setText("Meine Aufgaben Refresh");
        btnMyTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyTasksActionPerformed(evt);
            }
        });

        txaTaskDescription.setEditable(false);
        txaTaskDescription.setBackground(new java.awt.Color(18, 110, 99));
        txaTaskDescription.setColumns(20);
        txaTaskDescription.setForeground(new java.awt.Color(145, 237, 228));
        txaTaskDescription.setRows(5);
        scpTXATaskDescription.setViewportView(txaTaskDescription);

        btnTaskFinish.setBackground(new java.awt.Color(18, 110, 99));
        btnTaskFinish.setForeground(new java.awt.Color(145, 237, 228));
        btnTaskFinish.setText("Abgabe");
        btnTaskFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskFinishActionPerformed(evt);
            }
        });

        lstAllTasks.setBackground(new java.awt.Color(18, 110, 99));
        lstAllTasks.setForeground(new java.awt.Color(145, 237, 228));
        lstAllTasks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scpLSTAllTasks.setViewportView(lstAllTasks);

        jButton1.setBackground(new java.awt.Color(18, 110, 99));
        jButton1.setForeground(new java.awt.Color(145, 237, 228));
        jButton1.setText("Aufgabe Anzeigen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnQuestion.setBackground(new java.awt.Color(18, 110, 99));
        btnQuestion.setForeground(new java.awt.Color(145, 237, 228));
        btnQuestion.setText("Frage");
        btnQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionActionPerformed(evt);
            }
        });

        lblVonUser.setForeground(new java.awt.Color(145, 237, 228));
        lblVonUser.setText("Von User: ");

        lblEingeschätzteZeit.setForeground(new java.awt.Color(145, 237, 228));
        lblEingeschätzteZeit.setText("EIngeschätzte Zeit: ");

        txfVonUser.setEditable(false);
        txfVonUser.setBackground(new java.awt.Color(18, 110, 99));
        txfVonUser.setForeground(new java.awt.Color(145, 237, 228));

        txfEingeschätzteZeit.setBackground(new java.awt.Color(18, 110, 99));
        txfEingeschätzteZeit.setForeground(new java.awt.Color(145, 237, 228));

        txfTatsaechlicheZeit.setBackground(new java.awt.Color(18, 110, 99));
        txfTatsaechlicheZeit.setForeground(new java.awt.Color(145, 237, 228));

        lblTatsaechlicheZeit.setBackground(new java.awt.Color(145, 237, 228));
        lblTatsaechlicheZeit.setForeground(new java.awt.Color(145, 237, 228));
        lblTatsaechlicheZeit.setText("Bearbeitungs Zeit: ");

        javax.swing.GroupLayout PanelTaskBackgroundLayout = new javax.swing.GroupLayout(PanelTaskBackground);
        PanelTaskBackground.setLayout(PanelTaskBackgroundLayout);
        PanelTaskBackgroundLayout.setHorizontalGroup(
            PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                        .addComponent(btnNewTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMyTasks))
                    .addComponent(scpLSTAllTasks))
                .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaskBackgroundLayout.createSequentialGroup()
                                .addComponent(btnQuestion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTaskFinish)
                                .addGap(6, 6, 6))
                            .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                                .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaskBackgroundLayout.createSequentialGroup()
                                        .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(lblVonUser)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txfVonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton1))
                                        .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnTaskAnsichtExit))
                                            .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(lblEingeschätzteZeit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txfEingeschätzteZeit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(scpTXATaskDescription))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaskBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTatsaechlicheZeit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfTatsaechlicheZeit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PanelTaskBackgroundLayout.setVerticalGroup(
            PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewTask)
                    .addComponent(btnMyTasks)
                    .addComponent(btnTaskAnsichtExit)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTaskBackgroundLayout.createSequentialGroup()
                        .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVonUser)
                            .addComponent(txfVonUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEingeschätzteZeit)
                            .addComponent(txfEingeschätzteZeit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpTXATaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTatsaechlicheZeit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTatsaechlicheZeit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTaskFinish)
                            .addComponent(btnQuestion)))
                    .addComponent(scpLSTAllTasks))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTaskBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTaskBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaskAnsichtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskAnsichtExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnTaskAnsichtExitActionPerformed

    private void btnNewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTaskActionPerformed
        //hier kann man das Fenster für neue Tasks öffnen, damit das nicht immer sichtbar ist.
    }//GEN-LAST:event_btnNewTaskActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Markiertes Element aus Liste aus Datenbank holen und in "txaTaskDescription" eintragen
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMyTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyTasksActionPerformed
        // wenn man zwei Clients hat, das man die Tasks aktuallisieren kann
    }//GEN-LAST:event_btnMyTasksActionPerformed

    private void btnQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionActionPerformed
        // öffnet ebenfalls ein GUINewTask Fenster allerdings mit der Ausgewählten Task bereits drin und An ist die Person welche die Aufgabe gestellt hat
    }//GEN-LAST:event_btnQuestionActionPerformed

    private void btnTaskFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskFinishActionPerformed
        // Task wird als Fertig für Ersteller markiert und die Stunden gehen auf das Konto von der Person welche es erledigt hat.
    }//GEN-LAST:event_btnTaskFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITaskAnsicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITaskAnsicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITaskAnsicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITaskAnsicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITaskAnsicht().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTaskBackground;
    private javax.swing.JButton btnMyTasks;
    private javax.swing.JButton btnNewTask;
    private javax.swing.JButton btnQuestion;
    private javax.swing.JButton btnTaskAnsichtExit;
    private javax.swing.JButton btnTaskFinish;
    private javax.swing.ButtonGroup btngFinishQuestion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEingeschätzteZeit;
    private javax.swing.JLabel lblTatsaechlicheZeit;
    private javax.swing.JLabel lblVonUser;
    private javax.swing.JList<String> lstAllTasks;
    private javax.swing.JScrollPane scpLSTAllTasks;
    private javax.swing.JScrollPane scpTXATaskDescription;
    private javax.swing.JTextArea txaTaskDescription;
    private javax.swing.JTextField txfEingeschätzteZeit;
    private javax.swing.JTextField txfTatsaechlicheZeit;
    private javax.swing.JTextField txfVonUser;
    // End of variables declaration//GEN-END:variables
}
