package com.mycompany.raptortodo;

public class GUIChangePassword extends javax.swing.JFrame {

    ControlGUI ControlGUI1;

    public GUIChangePassword(ControlGUI aControlGUI) {
        ControlGUI1 = aControlGUI;
        initComponents();
    }

    public void setUsername(String username) {
        txfUsername.setText(username);
    }

    //gibt Text zurück
    public String getUsername() {
        return txfUsername.getText();
    }

    public String getOldPassword() {
        return txfOldPassword.getText();
    }

    public String getNewPassword() {
        return txfNewPassword.getText();
    }

    public String getNewPasswordRepeat() {
        return txfNewPasswordRepeat.getText();
    }

    public void GUIChangePasswordClearAll() {
        txfUsername.setText("");
        txfOldPassword.setText("");
        txfNewPassword.setText("");
        txfNewPasswordRepeat.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGUIChangePasswordBackground = new javax.swing.JPanel();
        lblNewPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblOldPassword = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        lblNewPasswordRepeat = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        txfOldPassword = new javax.swing.JTextField();
        txfNewPassword = new javax.swing.JTextField();
        txfNewPasswordRepeat = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passwort Entern");
        setMinimumSize(new java.awt.Dimension(406, 193));

        panelGUIChangePasswordBackground.setBackground(new java.awt.Color(40, 40, 40));
        panelGUIChangePasswordBackground.setMaximumSize(new java.awt.Dimension(475, 275));
        panelGUIChangePasswordBackground.setMinimumSize(new java.awt.Dimension(475, 275));
        panelGUIChangePasswordBackground.setPreferredSize(new java.awt.Dimension(475, 275));

        lblNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(145, 237, 228));
        lblNewPassword.setText("Neues Passwort");
        lblNewPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblNewPassword.setMaximumSize(new java.awt.Dimension(199, 32));
        lblNewPassword.setMinimumSize(new java.awt.Dimension(199, 32));
        lblNewPassword.setPreferredSize(new java.awt.Dimension(199, 32));

        lblUsername.setForeground(new java.awt.Color(145, 237, 228));
        lblUsername.setText("Benutzername:");

        lblOldPassword.setForeground(new java.awt.Color(145, 237, 228));
        lblOldPassword.setText("Altes Passwort:");

        lblNewPass.setForeground(new java.awt.Color(145, 237, 228));
        lblNewPass.setText("Neues Passwort:");

        lblNewPasswordRepeat.setForeground(new java.awt.Color(145, 237, 228));
        lblNewPasswordRepeat.setText("Passwort wiederholen:");

        txfUsername.setEditable(false);
        txfUsername.setBackground(new java.awt.Color(18, 110, 99));
        txfUsername.setForeground(new java.awt.Color(145, 237, 228));

        txfOldPassword.setBackground(new java.awt.Color(18, 110, 99));
        txfOldPassword.setForeground(new java.awt.Color(145, 237, 228));

        txfNewPassword.setBackground(new java.awt.Color(18, 110, 99));
        txfNewPassword.setForeground(new java.awt.Color(145, 237, 228));

        txfNewPasswordRepeat.setBackground(new java.awt.Color(18, 110, 99));
        txfNewPasswordRepeat.setForeground(new java.awt.Color(145, 237, 228));

        btnChangePassword.setBackground(new java.awt.Color(18, 110, 99));
        btnChangePassword.setForeground(new java.awt.Color(145, 237, 228));
        btnChangePassword.setText("Change password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(18, 110, 99));
        btnCancel.setForeground(new java.awt.Color(145, 237, 228));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGUIChangePasswordBackgroundLayout = new javax.swing.GroupLayout(panelGUIChangePasswordBackground);
        panelGUIChangePasswordBackground.setLayout(panelGUIChangePasswordBackgroundLayout);
        panelGUIChangePasswordBackgroundLayout.setHorizontalGroup(
            panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGUIChangePasswordBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGUIChangePasswordBackgroundLayout.createSequentialGroup()
                        .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNewPass)
                            .addComponent(lblNewPasswordRepeat)
                            .addComponent(lblOldPassword)
                            .addComponent(lblUsername))
                        .addGap(41, 41, 41)
                        .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGUIChangePasswordBackgroundLayout.createSequentialGroup()
                                .addComponent(btnChangePassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addComponent(txfNewPasswordRepeat)
                            .addComponent(txfNewPassword)
                            .addComponent(txfOldPassword)
                            .addComponent(txfUsername)))
                    .addGroup(panelGUIChangePasswordBackgroundLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelGUIChangePasswordBackgroundLayout.setVerticalGroup(
            panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGUIChangePasswordBackgroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPassword)
                    .addComponent(txfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPass)
                    .addComponent(txfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPasswordRepeat)
                    .addComponent(txfNewPasswordRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGUIChangePasswordBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnCancel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGUIChangePasswordBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGUIChangePasswordBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        ControlGUI1.ChangePasswordBtn();
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ControlGUI1.setGUIChangePasswordInvisible();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblNewPasswordRepeat;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelGUIChangePasswordBackground;
    private javax.swing.JTextField txfNewPassword;
    private javax.swing.JTextField txfNewPasswordRepeat;
    private javax.swing.JTextField txfOldPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
